### ISSUE TITLE
php 8.3

### ISSUE THREAD

**Issue by rabol** [kirilcvetkov/tesla-api#1]
Hi 

Any plans on supporting php 8.3 ?

**Comment by kirilcvetkov** [comment]
Absolutely! I'll upgrade it soon.

**Comment by kirilcvetkov** [comment]
What's breaking on php v8.3?

**Comment by rabol** [comment]
Nothing is breaking, I just got an error during install that I have the wrong version of php

**Comment by kirilcvetkov** [comment]
I'll check it out. Thanks for letting me know.

**Comment by kirilcvetkov** [comment]
I've successfully tested with v8.3. Please make sure to run `composer update` and compare your code with the samples in the README as I've updated its contents.
Closing issue. Please open another one if you have other issues. Thanks.
